1
9
25
{ 1, 3, 5 }
{ 1, 3, 22 }
{ 1, 0, 6 }
{ 0 to 1, 0 to 2, 0 to 3, 0 to 4, 0 to 5, 0 to 6, 0 to 7, 0 to 8, 0 to 9 }
Unhandled blame while running :Map
Expected a callable
Expected the callable to take 1 argument
Expected an iterable
4
9
25
64
{ 4, 64 }
{ 2, -2 }
{ "A", "B" }
Unhandled blame while running :Filter
Expected a callable
Expected the callable to take 1 argument
Expected an iterable
10
80
Expected a callable
Expected the callable to take 2 argument
Unhandled blame while running :Reduce
